steps:
 - name: gcr.io/cloud-builders/docker
   args: [ build, -t, gcr.io/$PROJECT_ID/phillip, . ]
 - name: gcr.io/cloud-builders/gcloud
   args: [ compute, instance-groups, managed, rolling-action, restart, phillip-instance-group, --zone=us-west1-b ]

images:
 - gcr.io/$PROJECT_ID/phillip
